// Seed data: identity, policies, and wedge workflow templates (Blueprint Phase 0/1).
import { OrgUser, Policy, WorkflowTemplate, PlanStep } from './types';

export const SEED_USERS: OrgUser[] = [
  { id: 'u-1', name: 'Ava Operations', email: 'ava@acme.internal', roles: ['Operations Lead', 'Operations Approver'], title: 'Head of Operations' },
  { id: 'u-2', name: 'Ben Rivera', email: 'ben@acme.internal', roles: ['CS Lead', 'Customer Success'], title: 'CS Team Lead' },
  { id: 'u-3', name: 'Cara Finance', email: 'cara@acme.internal', roles: ['Finance Approver', 'Controller'], title: 'Financial Controller' },
  { id: 'u-4', name: 'Dev Ops', email: 'dev@acme.internal', roles: ['Engineering', 'Senior Operator'], title: 'Platform Engineer' },
  { id: 'u-5', name: 'Sam Auditor', email: 'sam@acme.internal', roles: ['Operations Auditor', 'Admin'], title: 'Compliance Officer' },
];

export const SEED_POLICIES: Policy[] = [
  {
    id: 'P-1',
    name: 'External commitments require Finance approval',
    description: 'Any purchase, contract, invoice payment, or commitment above $5,000 must pass a Finance Approver gate before execution.',
    scope: 'approval',
    rule: 'amount > 5000 AND workflow in (purchase, invoice, contract) => require Finance Approver',
    action_when_denied: 'deny',
    enabled: true,
    version: 1,
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'P-2',
    name: 'High/critical risk requires human approval',
    description: 'Work items classified high or critical must have a person approve execution. Agents cannot authorize high-impact actions.',
    scope: 'workflow',
    rule: 'risk in (high, critical) AND action=execute => actor.type must be person',
    action_when_denied: 'deny',
    enabled: true,
    version: 1,
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'P-3',
    name: 'Write operations are idempotent and duplicate-protected',
    description: 'Every connected write during autonomy must carry an idempotency key, retry behavior, and duplicate protection.',
    scope: 'action',
    rule: 'action in (write, insert, update, execute) AND mode=bounded_autonomy => require idempotency key',
    action_when_denied: 'escalate',
    enabled: true,
    version: 1,
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'P-4',
    name: 'AI output is an untrusted proposal',
    description: 'Model output never directly executes. It produces a proposal the control plane validates. Distinguishable at all times.',
    scope: 'action',
    rule: 'actor.type = agent => proposal only; execute requires validated plan',
    action_when_denied: 'deny',
    enabled: true,
    version: 1,
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'P-5',
    name: 'Sensitive data access is role-filtered',
    description: 'Finance, HR, PII, and export reads require an Auditor, Admin, or Owner role.',
    scope: 'data',
    rule: 'action in (read:finance, read:hr, read:pii, export) => role in (Auditor, Admin, Owner)',
    action_when_denied: 'deny',
    enabled: true,
    version: 1,
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'P-6',
    name: 'Irreversible side effects need rollback/compensation',
    description: 'Payment, send, post, delete, sign, and commit actions require a documented rollback or compensation plan.',
    scope: 'workflow',
    rule: 'external_side_effects contains (pay, send, post, delete, sign, commit) AND action=execute => required rollback note',
    action_when_denied: 'escalate',
    enabled: true,
    version: 1,
    created_at: '2026-01-01T00:00:00.000Z',
  },
];

function planShell(steps: Array<{ s: string; c: string }>): PlanStep[] {
  return steps.map((st, i) => ({
    id: `tpl-${(i + 1).toString().padStart(2, '0')}`,
    summary: st.s,
    capability: st.c,
    mode: 'ai_prepares',
    prerequisites: i > 0 ? [steps[i - 1].s] : [],
    executed: false,
  }));
}

export const SEED_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'wf-customer-onboarding',
    name: 'Customer Onboarding',
    category: 'Revenue',
    description: 'Stand up a new customer end-to-end: account, contracts, credentials, kickoff.',
    risk_class: 'medium',
    required_capabilities: ['crm:write', 'contract:issue', 'iam:provision', 'email:send'],
    applicable_policy_ids: ['P-1', 'P-2', 'P-4', 'P-6'],
    default_control_mode: 'human_approves',
    plan_shell: planShell([
      { s: 'Create customer record in CRM with verified account details', c: 'crm:write' },
      { s: 'Issue contract draft from approved template and route for signature', c: 'contract:issue' },
      { s: 'Provision workspace, SSO, and initial user seats', c: 'iam:provision' },
      { s: 'Send welcome package and schedule kickoff', c: 'email:send' },
    ]),
    side_effect_hints: ['New customer contract issued', 'Seats provisioned (billed)'],
    value_hypothesis: 'Reduce new-customer setup from 5 days to under 2 with full audit evidence.',
  },
  {
    id: 'wf-incident-resolution',
    name: 'Incident Resolution',
    category: 'Operations',
    description: 'Triage, route, fix, and verify a reported incident to SLA.',
    risk_class: 'high',
    required_capabilities: ['ticketing:write', 'monitoring:read', 'runbook:execute'],
    applicable_policy_ids: ['P-2', 'P-4', 'P-5'],
    default_control_mode: 'ai_prepares',
    plan_shell: planShell([
      { s: 'Classify incident severity and page the right on-call owner', c: 'ticketing:write' },
      { s: 'Pull diagnostics from monitoring and correlate recent changes', c: 'monitoring:read' },
      { s: 'Draft incident summary and proposed fix for human confirmation', c: 'runbook:execute' },
      { s: 'Execute verified fix, update ticket, and produce post-incident review', c: 'ticketing:write' },
    ]),
    side_effect_hints: ['Pages/notifications sent to on-call'],
    value_hypothesis: 'Cut mean-time-to-resolve by 40% with documented evidence per incident.',
  },
  {
    id: 'wf-invoice-exception',
    name: 'Invoice Exception',
    category: 'Finance',
    description: 'Resolve invoice mismatches, approvals, and payment holds.',
    risk_class: 'high',
    required_capabilities: ['finance:read', 'finance:write', 'approval:route', 'vendor:api'],
    applicable_policy_ids: ['P-1', 'P-2', 'P-3', 'P-4', 'P-5', 'P-6'],
    default_control_mode: 'human_approves',
    plan_shell: planShell([
      { s: 'Reconcile invoice line items against PO and receipt', c: 'finance:read' },
      { s: 'Compute discrepancy report and proposed resolution', c: 'finance:write' },
      { s: 'Route to Finance Approver with policy check evidence', c: 'approval:route' },
      { s: 'Post resolution, update vendor record, and confirm payment status', c: 'vendor:api' },
    ]),
    side_effect_hints: ['Payment released', 'Vendor record updated'],
    value_hypothesis: 'Resolve exception invoices under 1 business day with a full evidence trail.',
  },
  {
    id: 'wf-vendor-purchase-review',
    name: 'Vendor / Purchase Review',
    category: 'Procurement',
    description: 'Vet a purchase request against budget, policy, and vendor record.',
    risk_class: 'critical',
    required_capabilities: ['procurement:read', 'finance:read', 'approval:route'],
    applicable_policy_ids: ['P-1', 'P-2', 'P-4', 'P-6'],
    default_control_mode: 'human_approves',
    plan_shell: planShell([
      { s: 'Verify vendor status, budget line, and contract terms', c: 'procurement:read' },
      { s: 'Evaluate spend against policy threshold and flag exceptions', c: 'finance:read' },
      { s: 'Package decision memo for Finance and Ops approval', c: 'approval:route' },
    ]),
    side_effect_hints: ['PO issued / payment committed'],
    value_hypothesis: 'Route purchases with a 3-day approval SLA and full spend visibility.',
  },
  {
    id: 'wf-contractor-onboarding',
    name: 'Contractor Onboarding',
    category: 'People',
    description: 'Onboard a contractor through HR, procurement, and IT in sequence.',
    risk_class: 'medium',
    required_capabilities: ['hr:write', 'procurement:write', 'iam:provision', 'email:send'],
    applicable_policy_ids: ['P-1', 'P-2', 'P-4', 'P-5'],
    default_control_mode: 'ai_prepares',
    plan_shell: planShell([
      { s: 'Create contractor record and classify engagement type', c: 'hr:write' },
      { s: 'Generate contract and route for signature', c: 'procurement:write' },
      { s: 'Provision access scoped to engagement end date', c: 'iam:provision' },
      { s: 'Send onboarding packet and schedule intake', c: 'email:send' },
    ]),
    side_effect_hints: ['Contract issued', 'Access provisioned'],
    value_hypothesis: 'Complete contractor onboarding in one business day with expiry-scoped access.',
  },
  {
    id: 'wf-contract-obligation-tracker',
    name: 'Contract Obligation Tracker',
    category: 'Legal',
    description: 'Extract and track obligations with renewal alerts and evidence.',
    risk_class: 'medium',
    required_capabilities: ['doc:read', 'obligation:write', 'calendar:write'],
    applicable_policy_ids: ['P-2', 'P-4', 'P-5'],
    default_control_mode: 'ai_suggests',
    plan_shell: planShell([
      { s: 'Extract obligations and dates from contract document', c: 'doc:read' },
      { s: 'Register obligations in tracker with owners and SLA', c: 'obligation:write' },
      { s: 'Schedule renewal and review reminders with evidence links', c: 'calendar:write' },
    ]),
    side_effect_hints: ['Calendar events created'],
    value_hypothesis: 'Zero missed renewals via tracked obligations with provenance on every fact.',
  },
];

export const SEED_ORG_CONTEXT = 'Acme Industries (1,400 employees) — Sales, Delivery, Finance, IT, Legal as primary stakeholders.';

export const makeActor = (u: OrgUser) => ({
  type: 'person' as const,
  identity: u.id,
  display: `${u.name} (${u.roles[0] || 'Member'})`,
});